CREATE SCHEMA IF NOT EXISTS `sitoo_test_assignment`
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- CREATE TABLE IF NOT EXISTS `sitoo_test_assignment`.`product`
-- (
--     `id`  INT UNSIGNED   NOT NULL AUTO_INCREMENT,
--     `title`          VARCHAR(32)    NOT NULL,
--     `sku`            VARCHAR(32)    NOT NULL,
--     `description`    VARCHAR(1024)  NULL,
--     `price`          DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
--     `created_at`     DATETIME       NOT NULL,
--     `updated_at`     DATETIME       NOT NULL,
--     `deleted_at`     DATETIME       NULL,
--     PRIMARY KEY (`id`),
--     UNIQUE INDEX (`sku` ASC),
--     INDEX (`created_at`)
-- );
-- CREATE TABLE IF NOT EXISTS `sitoo_test_assignment`.`product_barcode`
-- (
--     `id` INT UNSIGNED NOT NULL,
--     `barcode`    VARCHAR(32)  NOT NULL,
--     PRIMARY KEY (`id`, `barcode`),
--     UNIQUE INDEX (`barcode`)
-- );
-- CREATE TABLE IF NOT EXISTS `sitoo_test_assignment`.`product_attribute`
-- (
--     `id` INT UNSIGNED NOT NULL,
--     `name`       VARCHAR(16)  NOT NULL,
--     `value`      VARCHAR(32)  NOT NULL,
--     PRIMARY KEY (`id`, `name`)
-- );
