version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    command: --init-file /data/application/create_database.sql
    volumes:
      - ./create_database.sql:/data/application/create_database.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'
