version: '3.3'

services:
  app:
    container_name: app
    build: .
    depends_on:
      - db
    ports:
      - '8080:8080'
    expose:
      - '8080'
    links:
      - db
  db:
    container_name: db
    image: mysql:latest
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping']
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    command: --init-file /data/application/create_database.sql
    volumes:
      - ./create_database.sql:/data/application/create_database.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'